# Generated by Django 5.1.1 on 2024-12-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_teacher_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
