# Generated by Django 5.1.1 on 2024-12-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_teacher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
